#
# define scoring probe
#
 /score/create/probe Probes 5 mm
 /score/probe/locate 0. 0. 0. mm

#
# define flux scorers and filter
#
/score/quantity/flatSurfaceCurrent Flux
/score/filter/particle Flux neutron

/score/close
#
# define histograms
#
/analysis/setFileName Mytest
/analysis/h1/create primary primary 1000 0.01 2.5 MeV
#/analysis/h1/create Flux Probes_volFlux 100 0.01 2.5 MeV ! log
/analysis/h1/create Flux Probes_volFlux 1000 0.01 2.5 MeV
#
# filling histograms
#
/score/fill1D 1 Probes Flux

/run/beamOn 10000